backend:
  # name: test-repo
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

# Uncomment local_backend when you need to develop in your local
local_backend: true # run npx netlify-cms-proxy-server for local testing
logo_url: ../assets/pirate-logo-bw.svg
media_folder: "static/assets"
public_folder: "/assets"
# publish_mode: editorial_workflow
# site_url: ""
# display_url: ""
show_preview_links: false

collections:

  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    editor:
      preview: false
    label: "Site Posts" # Used in the UI
    label_singular: "Site Post" # Used in the UI, ie: "New Post"
    description: >
      Create stuff for your website here.
    folder: "static/content/posts"
    slug: "{{slug}}"
    summary: "{{title}} — {{year}}/{{month}}/{{day}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: "Template",
          name: "template",
          widget: "hidden",
          default: "blog-post",
        }


      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          hint: "Start slug with /. Use only alphanumeric characters, - and _. Avoid spaces in any cases.",
          default: "/",
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
          format: "YYYY-MM-DD HH:mm",
        }



      - { label: "SEO Description", name: "description", widget: "text" }
      - { label: "Category", name: "category", widget: "list", collapsed: true, default: "Default", required: false, add_to_top: true, field: {label: Category, name: name, widget: string, add_to_top: true,}}














      - { label: "Make Post Shareable?", name: "shareable", widget: "boolean", default: false, required: false }
      - { label: "Make Feature Image Zoom", name: "showZoom", widget: "boolean", default: false, required: false }
      - { label: "Turn on Page Level Nav", name: "showPageNav", widget: "boolean", default: true, required: false }
      - { label: "Spotlight on Homepage", name: "spotlight", widget: "boolean", default: false, required: false }









      - { label: "Page Tags", name: "tags", widget: "list", collapsed: true, default: "tagged", required: false, add_to_top: true, field: {label: Tag, name: name, widget: string, add_to_top: true, collapsed: true,}}

      - {
              label: "YouTube",
              name: "youtube",
              widget: "object",
              collapsed: true, # Set to true to collapse panel by default
            fields: [
              { label: "YouTube Url", name: "youtuber", widget: "string",required: false },
              { label: "YouTube Start", name: "youtubestart", widget: "string", required: false },
              { label: "YouTube End", name: "youtubeend", widget: "string", required: false },
              { label: "YouTube Audio", name: "youtuber2", widget: "string", required: false },
              { label: "YouTube Audio Start", name: "audiostart", widget: "string", required: false },
              { label: "YouTube Audio End", name: "audioend", widget: "string", required: false },
              { label: "YouTube Audio Title", name: "audiotitle", widget: "string", required: false },
              { label: "YouTube Mute", name: "youtubemute", widget: "boolean", default: false, required: false },
              { label: "YouTube AutoPlay", name: "youtubeautostart", widget: "boolean", default: false, required: false },
              { label: "YouTube Loop", name: "youtubeloop", widget: "boolean", default: true, required: false },
              { label: "YouTube Controls", name: "youtubecontrols", widget: "boolean", default: false, required: false },
              { label: "YouTube Use Custom Controls", name: "customcontrols", widget: "boolean", default: false, required: false },
              { label: "YouTube Click To Play", name: "clicktoplay", widget: "boolean", default: false, required: false }
            ]
          }





      
      - {
          label: "Featured Image",
          name: "featuredImage",
          widget: "image",
          hint: "The primary image used for all social media, blog previews and the feature image at the top of the post",
          required: false,
          tagname: "",
          # default: "/assets/transparent.png"
        }
      - {
          label: "Underlay Image",
          name: "underlayImage",
          widget: "image",
          hint: "This is used to put a transparent png over the video but under the animation layer",
          required: false,
          tagname: "",
          # default: "/assets/transparent.png"
        }
      - {
          label: "SVG",
          name: "svgImage",
          widget: "image",
          hint: "This is the animation layer where your animated or static SVG image goes - it is on the top of the stack",
          required: false,
          tagname: "",
          # default: "/assets/null.svg"
        }




      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          required: false,
          hint: "Main content goes here.",
        }
        

        
  - name: "team"
    editor:
      preview: false
    label: "Pirate Posts"
    label_singular: "Pirate Post"
    description: >
      Pirate Posts - your content on Pirate
    folder: "static/content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "team"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Team Member Name", name: "name", widget: "string"}
      - {label: "Job Title", name: "jobTitle", widget: "string"}
      - {label: "Credentials", name: "credentials", widget: "string"}
      - {label: "Page Order", name: "order", widget: "number"}
      - {label: "Team Image", name: "profilePicture", widget: "image", required: false,}
      - {label: "Body", name: "body", widget: "markdown"}






  - label: "HomePage"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        file: "static/content/pages/index.md"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "index-page",
            }
          - { label: "Slug", name: "slug", widget: "hidden", default: "/" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Featured Image", name: "featuredImage", widget: "image", required: false }
          

          - { label: "Secondary Image", name: "secondaryImage", widget: "image", hint: "this image is used for the profile photo in the info section", required: false }
          - { label: "Underlay Image", name: "underlayImage", widget: "image", required: false }

          - { label: "Body", name: "body", widget: "markdown" }

                
      
      

  

  - name: settings
    editor:
      preview: false
    label: Settings
    files:
      - name: general
        label: General
        file: "static/data/site.json"
        fields:
          - label: meta
            name: meta
            widget: object
            fields:
              - widget: string
                name: title
                label: Site Title
                required: true
              - widget: hidden
                name: titleTemplate
                label: Title Template (ignore)
                default: "%s"
                required: true
              - widget: string
                name: siteUrl
                label: Website URL
                required: true
              - widget: text
                name: description
                label: Description
                default: ""
                required: false
              - widget: string
                name: twitterUsername
                label: Twitter user (no '@' justthename)
                required: false
              - widget: string
                name: companyname
                label: Company Name or Site Name
                required: true


              - widget: "number"
                label: "Number of posts on HOME PAGE"
                name: "homecount"
                default: 5
                value_type: "int"
                min: 1
                max: 51
                step: 2
                hint: "Max #50"


              - widget: "number"
                label: "Number of posts on other pages"
                name: "postcount"
                default: 18
                value_type: "int"
                min: 1
                max: 51
                step: 2
                hint: "Max #50"


              - widget: boolean
                name: showNav 
                label: Show Top Nav
                required: false

              - widget: boolean
                name: showNav2 
                label: Show Side Nav
                required: false
                
              - widget: boolean
                name: showDates
                label: Show Dates
                required: false



              - widget: boolean
                name: showSearch
                label: Show Search Icon 
                required: false

              - widget: boolean
                name: showSwipe
                label: Show Swipe Icon
                required: false





              - widget: string
                name: font1
                label: Google Font
                required: false
              - widget: image
                name: image
                label: Site Background Image
                required: false
                default: "/assets/default-og-image.webp"
              - widget: image
                name: iconimage
                label: Site Logo (should be SVG if at all possible)
                required: false
              - widget: image
                name: icon512
                label: Site Icon 512x512
                hint: "This is for icon usage in various locations"
                required: false
                
              




    

      - label: Menu Navigation
        name: menuNavigation
        editor:
          preview: false
        file: "static/data/menu.json"
        fields:
          - label: Menu Items
            name: menuItems
            widget: list
            collapsed: true
            hint: "Here you can add menu items, Click on 'Add menu item'"
            fields:
              - widget: string
                name: menutitle
                label: Menu Title
                required: true
                hint: "The title that appears in the menu"
              - widget: string
                name: url
                label: url
                required: true
                hint: "add the url of the menu item"

  - label: "Appearance"
    name: "appearance"
    editor:
      preview: false
    identifier_field: "name"
    files:
      - label: "User Styles"
        name: "userStyles"
        file: "static/data/userStyles.json"
        fields:
          - label: "Override Site Styles"
            name: "userStyles"
            widget: "markdown"
            hint: "Additional CSS can be written here, overwriting the site's default styles."

      - label: "Default Theme"
        name: "themescolors"
        file: "static/data/default-colors.json"
        fields:
          - label: "siteColor"
            name: "siteColor"
            widget: "color"
            enableAlpha: true
            allowInput: true
            hint: "Don't know what this is"

          - label: "headerColor"
            name: "headerColor"
            widget: "color"
            enableAlpha: true
            allowInput: true

          - label: "text"
            name: "text"
            widget: "color"
            enableAlpha: true
            allowInput: true








      - label: "Dark Theme"
        name: "darkthemescolors"
        file: "static/data/dark-theme-colors.json"
        fields:
          - label: "siteColor"
            name: "siteColor"
            widget: "color"
            enableAlpha: true
            allowInput: true
            hint: "Don't know what this is"

          - label: "headerColor"
            name: "headerColor"
            widget: "color"
            enableAlpha: true
            allowInput: true

          - label: "text"
            name: "text"
            widget: "color"
            enableAlpha: true
            allowInput: true

